### ISSUE TITLE
 × Module not found: Can't resolve 'fsevents' in 

### ISSUE THREAD

**Issue by ipseonet** [rspack-contrib/rspack-examples#155]
Trying to use the express example, but fsevents gets in the way and the server does not start. It returns this error:
`
  × Module not found: Can't resolve 'fsevents' in '//rsbuild.one/node_modules/@rsbuild/core/compiled/chokidar'
      ╭─[4366:23]
 4364 │     464: (module) => {
 4365 │       "use strict";
 4366 │       module.exports = require("fsevents");
      ·                        ───────────────────
 4367 │     },
 4368 │     37: (module) => {
      ╰────
`
I dont use MacOS and have fsevents inside of optionalDependencies in my package.json but the server still tries to use fsevents.

Any suggestions?

**Comment by chenjiahan** [comment]
Rsbuild has been updated to chokidar v4 and no longer depends on `fsevents`, see: https://github.com/web-infra-dev/rsbuild/pull/3960
