### ISSUE TITLE
Preact refresh work not as expected.

### ISSUE THREAD

**Issue by cbbfcd** [rspack-contrib/rspack-examples#157]
config as:

<img width="429" alt="image" src="https://github.com/user-attachments/assets/bff593c2-8099-4aaf-9e55-e578b52a51ae">

and got the error:

<img width="1063" alt="image" src="https://github.com/user-attachments/assets/4cd709f4-c452-4169-b7fe-4825b4dc5798">

so, entry `index.tsx` not be compiled?

**Comment by chenjiahan** [comment]
Hello. Please provide a reproduction repository or online demo. For background, see [Why reproductions are required](https://antfu.me/posts/why-reproductions-are-required). Thanks ❤️
