### ISSUE TITLE
vue3-jsx直接报错

### ISSUE THREAD

**Issue by chenyulun** [rspack-contrib/rspack-examples#163]
编译出来的文件`ref`直接丢失了？

![image](https://github.com/user-attachments/assets/488c56d1-6165-405d-9d60-55fdfe197bc8)

**Comment by chenyulun** [comment]
升级`@vue/babel-plugin-jsx`为`1.2.5`即可

说明这些案例都是没有测试过的，建议都自己去尝试一下

**Comment by chenjiahan** [comment]
I will fix this issue, thank you.

One problem is that it is difficult for us to ensure that all examples can be continuously available. If you find any problems, welcome to submit a PR ❤️.
