### ISSUE TITLE
Unexpected token `@`. Expected identifier, string literal, numeric literal

### ISSUE THREAD

**Issue by codersth** [rspack-contrib/rspack-examples#184]
无法使用注释。

    /**
     * @desc 提示消息 （只展示最新的消息）
     * @param {}
     */
    showNotify({ content, urlAndParams: { url, params }, id } = {}) {}

=========================日志================================
File: F:\developer\workspace\h5\xxxx\src\frontPage\views\index\Index.vue?vue&type=script&lang=js:1:1
  × Module build failed:
  ├─▶   ×   × Unexpected token `@`. Expected identifier, string literal, numeric literal or [ for the computed key
  │     │      ╭─[F:\developer\workspace\h5\xxxx\src\frontPage\views\index\Index.vue:930:1]
  │     │  927 │      * @desc 点击查看更多
  │     │  928 │      * @param {数据模块参数}
  │     │  929 │      */
  │     │  930 │     @GuestAndOrgInterceptors('guestAndLoginDialog')
  │     │      ·     ─
  │     │  931 │     onMore({ name, value, otherName, isOtherName } = {}) {
  │     │  932 │       if (value == 'DynamicBills') {
  │     │  932 │         localStorage.setItem('defaultMenu', 'dailyReview')
  │     │      ╰────
  │     │
  │
  ╰─▶ Syntax Error

**Comment by chenjiahan** [comment]
Hello. Please provide a reproduction repository or online demo. For background, see [Why reproductions are required](https://antfu.me/posts/why-reproductions-are-required). Thanks ❤️
